*java.security.PrivilegedActionException* *PrivilegedActionException* This excep

public class PrivilegedActionException
  extends    |java.lang.Exception|

|java.security.PrivilegedActionException_Description|
|java.security.PrivilegedActionException_Fields|
|java.security.PrivilegedActionException_Constructors|
|java.security.PrivilegedActionException_Methods|

================================================================================

*java.security.PrivilegedActionException_Constructors*
|java.security.PrivilegedActionException(Exception)|Constructs a new Privileged

*java.security.PrivilegedActionException_Methods*
|java.security.PrivilegedActionException.getCause()|Returns the the cause of th
|java.security.PrivilegedActionException.getException()|Returns the exception t
|java.security.PrivilegedActionException.toString()|

*java.security.PrivilegedActionException_Description*

This exception is thrown by doPrivileged(PrivilegedExceptionAction) and 
doPrivileged(PrivilegedExceptionAction, AccessControlContext context) to 
indicate that the action being performed threw a checked exception. The 
exception thrown by the action can be obtained by calling the getException 
method. In effect, an PrivilegedActionException is a "wrapper" for an exception 
thrown by a privileged action. 

As of release 1.4, this exception has been retrofitted to conform to the 
general purpose exception-chaining mechanism. The "exception thrown by the 
privileged computation" that is provided at construction time and accessed via 
the (|java.security.PrivilegedActionException|) method is now known as the 
cause, and may be accessed via the (|java.lang.Throwable|) method, as well as 
the aforementioned "legacy method." 


*java.security.PrivilegedActionException(Exception)*

public PrivilegedActionException(java.lang.Exception exception)

Constructs a new PrivilegedActionException wrapping the specific Exception. 

    exception - The exception thrown 

*java.security.PrivilegedActionException.getCause()*

public |java.lang.Throwable| getCause()

Returns the the cause of this exception (the exception thrown by the privileged 
computation that resulted in this PrivilegedActionException). 


    Returns: the cause of this exception. 
*java.security.PrivilegedActionException.getException()*

public |java.lang.Exception| getException()

Returns the exception thrown by the privileged computation that resulted in 
this PrivilegedActionException. 

This method predates the general-purpose exception chaining facility. The 
(|java.lang.Throwable|) method is now the preferred means of obtaining this 
information. 


    Returns: the exception thrown by the privileged computation that resulted in this 
             PrivilegedActionException. 
*java.security.PrivilegedActionException.toString()*

public |java.lang.String| toString()





